import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex">
          <div className="border-r border-r-gray-300/50 w-72 h-screen ">
            <div>holii</div>
          </div>
          <div className="bg-gray-100 grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
